
services:

  dependent-service:
    image: nginx:latest
    ports:
      - "8080:80"
    environment:
      TMP_TEST_GLOBAL_OVERRIDE: true

  project-develop:
    labels:
      norlab.dockerized-norlab.project.service: "develop override"
    environment:
      TMP_TEST_GLOBAL_OVERRIDE: true
    depends_on:
      - dependent-service

# .................................................................................................

# services:
#
#   project-develop:
#     labels:
#       norlab.dockerized-norlab.project.service: "develop override"
#
#   project-deploy:
#     labels:
#       norlab.dockerized-norlab.project.service: "deploy override"
#
#
#   project-ci-tests:
#     labels:
#       norlab.dockerized-norlab.project.service: "ci-tests override"
#
#
#   project-slurm:
#     labels:
#       norlab.dockerized-norlab.project.service: "slurm override"
#
